name: Build Docker Image and Push to Evolution Artifact Registry

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Evolution Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: anton.cr.cloud.ru
          username: a78354ff0bc6d98b309629a0930b7abd
          password: 8982b462ab6cf8ed82a26ebeaca1093b

      name: Build and push container image to cloud evolution registry
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: anton.cr.cloud.ru/intelligencebot:${{ github.sha }}
        file: ./Dockerfile
        context: ./